### ISSUE TITLE
Orthographe : "Il y a 1 années"

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/ClaroSupport#1]
_From @purplefish32 on January 18, 2016 10:42_

Constaté sur la v5 :
Sur un widget de page d'accueil on peut voir "Il y a 1 années" , quand c'est au singlulier il faut enlever le "s"

_Copied from original issue: claroline/Claroline#715_

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#83
