### ISSUE TITLE
ExoBundle : Papers are not saved when in a formative exercise

### ISSUE THREAD

**Issue by Elorfin** [claroline/ClaroSupport#19]
When the Exercise is formative, at the end, the Paper of the student is not saved.
Reported by UJM but not yet reproduced by Innova.

**Comment by marion42** [comment]
Do you reproduced the problem ?
Do you want I take a look on the problem ?

**Comment by Elorfin** [comment]
I just tried and there is no problem on my install. When I start to respond to a Formative exercise : 
- If I have an unfinished paper, this one is updated at the end of the Exercise
- If I have no unfinished paper, a new one is created at the beginning of the Exercise and is updated at the end.

So yes, give it a try please and tell me you results.

**Comment by charlotte42** [comment]
C'est quand on est pas en formatif que l'entité paper reste vide à la fin du passage de l'exercise.

It is when we are not training that the entity remains blank paper at the end of the passage of the exercise.

**Comment by Elorfin** [comment]
It works for any type of Exercise for me. So I will let you check this one.

**Comment by charlotte42** [comment]
En étant sur la branche V6 tu n'as pas ce souci ?

**Comment by charlotte42** [comment]
C'est pas l'entité Paper qui est vide mais Response

**Comment by marion42** [comment]
Duplicate with #25

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#101
