### ISSUE TITLE
Bug : potential problem for IE 

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/ClaroSupport#2]
_From @CPASimUSante on December 12, 2015 11:36_

there is a remaining `console.log(home.path);` in  /vendor/claroline/js/libraries.js that is loaded on every page.
This can be a problem for older IE that does not recognize console.log() and thus beak the use of js

Seen on latest 6.6.7 (don't know about previous versions)

_Copied from original issue: claroline/Claroline#714_

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#84
