### ISSUE TITLE
ExoBundle : Passsage questions exercice : indices

### ISSUE THREAD

**Issue by charlotte42** [claroline/ClaroSupport#29]
Finir d'ntégrer les indices dans le player angular

**Comment by Elorfin** [comment]
C'est à dire ?

**Comment by charlotte42** [comment]
On ne peut pas l'ouvrir avec une question asso et je crois que pour les autres types de questions il n'enlève pas les points.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#111
