### ISSUE TITLE
ExoBundle : Gestion questions/steps dans le player

### ISSUE THREAD

**Issue by charlotte42** [claroline/ClaroSupport#31]
Pouvoir changer l'ordre des questions dans une étape et les déplacer d'une step à l'autre
Importer des questions directement dans une step

**Comment by Elorfin** [comment]
Duplicate #19

**Comment by charlotte42** [comment]
(Je me suis trompé dans le copier collé...)
Pouvoir changer l'ordre des questions dans une étape et les déplacer d'une step à l'autre
Importer des questions directement dans une step

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#81

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#113
