### ISSUE TITLE
[Administration] Gestion des Utilisateurs

### ISSUE THREAD

**Issue by eddymarques** [claroline/ClaroSupport#39]
Claroline v6.8.4
La nouvelle interface de la Gestion des Utilisateurs côté Administrateur affiche une liste vide sous IE11 (et probablement sous Edge aussi)
![image](https://cloud.githubusercontent.com/assets/3414956/14201846/c7b77816-f7f4-11e5-8963-2a4e4984946d.png)

IE v11.0.9600.18231

**Comment by ngodfraind** [comment]
Ouch. Il va falloir que j'installe une vm... J'essaye de régler ça début de
semaine prochaine.

2016-04-01 10:30 GMT+02:00 eddymarques <notifications@github.com>:

> Claroline v6.8.4
> La nouvelle interface de la Gestion des Utilisateurs côté Administrateur
> affiche une liste vide sous IE11 (et probablement sous Edge aussi)
> [image: image]
> <https://cloud.githubusercontent.com/assets/3414956/14201846/c7b77816-f7f4-11e5-8963-2a4e4984946d.png>
>
> IE v11.0.9600.18231
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/ClaroSupport/issues/39>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#73
