### ISSUE TITLE
[Ticket Erreur]

### ISSUE THREAD

**Issue by eddymarques** [claroline/ClaroSupport#41]
La gestion d'erreur provoque elle-même une erreur.
En cliquant sur "Créer un ticket pour cette erreur", "Une erreur s'est produite apparaît"

Je vais tenter de récupérer un log là dessus

![image](https://cloud.githubusercontent.com/assets/3414956/14202349/b643aa3e-f7f7-11e5-900f-a096cb797ca1.png)

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#70
