### ISSUE TITLE
[ExoBundle] Liste des copies > Recherche par nom

### ISSUE THREAD

**Issue by eddymarques** [claroline/ClaroSupport#43]
La recherche par nom dans la liste des copies provoque une erreur.
Le problème se pose dans la version PHP, pas dans la version Angular.
Mais il n'est pas possible d'ouvrir les copies depuis la version Angular

![image](https://cloud.githubusercontent.com/assets/3414956/14202472/71eb611e-f7f8-11e5-8897-89ecf6615f2b.png)

**Comment by charlotte42** [comment]
J'ai corrigé pour la version php (pas encore push) mais par contre je comprend pas ton soucis sur la version angular?

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#68
