### ISSUE TITLE
[ExoBundle] Exercice "Player" sous IE

### ISSUE THREAD

**Issue by eddymarques** [claroline/ClaroSupport#44]
Lors de la réalisation d'un Exercice, IE affiche une alerte à chaque changement de page "Suivant"
![image](https://cloud.githubusercontent.com/assets/3414956/14207964/46c03e4a-f81d-11e5-8f75-ff6e0e6a57fe.png)

Problème similaire avec un compte connecté ou sans être identifié.
Ce problème n’apparaît pas sous Chrome et Firefox.

IE v. 11.0.9600

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#67
