### ISSUE TITLE
[ExoBundle] Modification des Paramètres impossible

### ISSUE THREAD

**Issue by eddymarques** [claroline/ClaroSupport#45]
La modification des Paramètres sur la dernière version des Exercices provoque une erreur.
Le bug semble être généralisé à tous les Exercices

Claroline (6.8.4)

![image](https://cloud.githubusercontent.com/assets/3414956/14244884/00cd2702-fa5e-11e5-9be9-e01146e9b1c3.png)

**Comment by david42** [comment]
Le tag 6.1.2 vient d'être publié afin de résoudre ce problème
