### ISSUE TITLE
Impossible d'éditer une question de type QCM

### ISSUE THREAD

**Issue by Elorfin** [claroline/ClaroSupport#46]
Il est impossible d'ouvrir le formulaire d'édition d'une question de type QCM (j'ai essayé avec le type Ouvert et l'édition est disponible, pour les autres je n'ai pas encore vérifié).

@marion42 @charlotte42 pourriez vous jetter un oeil ? Je ne vois pas d'où cela peut venir.

![bug-qcm](https://cloud.githubusercontent.com/assets/5363219/14275640/ff2ad80c-fb18-11e5-9d74-cf720b9c6fb9.jpg)

**Comment by charlotte42** [comment]
Normalement, Nicolas l'avait corrigé, tu es sur quelle branche ?

**Comment by ngodfraind** [comment]
En fait ça a planté à un moment, et la maj de symfony2 a réparer la chose
(mais mon bugfix s'est retrouvé cassé).
II suffit de changer le data_class d'un des formulaires (je ne sais plus
lequel), et une des ses 2 valeurs fonctionnera:

null
UJM\ExoBundle\Entity\TypeQCM

2016-04-05 10:35 GMT+02:00 Charlotte Pourquier <notifications@github.com>:

> Normalement, Nicolas l'avait corrigé, tu es sur quelle branche ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/ClaroSupport/issues/46#issuecomment-205718372>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by charlotte42** [comment]
Oui c'est le formulaire : InteractionQCMType

**Comment by Elorfin** [comment]
J'ai récupéré les dernière modification de la v6.

Si je remplace : 
'class' => 'UJM\\ExoBundle\\Entity\\TypeQCM',
'data_class' => 'UJM\\ExoBundle\\Entity\\TypeQCM',

Par : 
'class' => 'UJMExoBundle:TypeQCM',

ça fonctionne ;).

**Comment by charlotte42** [comment]
On peut le fermer lui, non ?

**Comment by Elorfin** [comment]
oui
