### ISSUE TITLE
Bug : Drag and drop not available in Resource manager

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/ClaroSupport#5]
_From @stmolivier on October 15, 2015 13:28_

When i create, upload new ressource (from the Desktop > Resource) in any workspace, i can't drag and drop after they are created/uploaded. I have to change page several times and come back so that i can drag and drop.

_Copied from original issue: claroline/Claroline#710_

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#87
